services:
  - type: web
    name: yoichi-store
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        generateValue: true
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_PASS
        sync: false
